version: '3'
services:
  camunda:
    build: ./Camunda/
    container_name: camunda_acmesky
    ports: 
      - 8080:8080
    networks:
      - acmesky-network
  camunda_workers:
    build: ./camunda-workers
    container_name: camunda_workers
    networks:
      - acmesky-network
    restart: unless-stopped
  geographical_distances:
    build: ./geographical-distances
    container_name: geographical_distances
    networks:
      - acmesky-network
    ports:
      - 5000:8080
    env_file:
      - ./geographical-distances/.env
  travel_company_1:
    build: ./travel-company
    container_name: travel_company_1
    networks:
      - acmesky-network
    ports:
      - 6001:8080

networks:
  acmesky-network:
    driver: bridge
    
