version: '3'
services:
  camunda:
    build: ./Camunda/
    container_name: camunda_acmesky
    ports: 
      - 8080:8080
    networks:
      - acmesky-network
  camunda_workers:
    build: ./camunda-workers
    container_name: camunda_workers
    networks:
      - acmesky-network
    restart: unless-stopped
  geographical_distances:
    build: ./geographical-distances
    container_name: geographical_distances
    networks:
      - acmesky-network
    ports:
      - 5000:8080
    env_file:
      - ./geographical-distances/.env
  travel_company_1:
    build: ./travel-company
    container_name: travel_company_1
    networks:
      - acmesky-network
    ports:
      - 6001:8080
  flight_company_1:
    build: ./flight-company
    container_name: flight_company_1
    networks:
      - acmesky-network
    ports:
      - 7001:8080
    env_file:
      - ./flight-company/.env
    environment:
      POSTGRES_DB: flightcompany1
      POSTGRES_HOST: flight_companies_db
    depends_on:
      - flight_companies_db
  flight_companies_db: # Shared postgres instance for flight companies
    image: postgres:13.2
    container_name: flight_companies_db
    env_file:
      - ./flight-company/.env
    volumes:
      - ./flight-company/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - acmesky-network

networks:
  acmesky-network:
    driver: bridge
    
