version: '3'
services:
  camunda:
    build: ./Camunda/
    container_name: camunda_acmesky
    ports: 
      - 8080:8080
    networks:
      - acmesky-network
  camunda_workers:
    build: ./camunda-workers
    container_name: camunda_workers
    networks:
      - acmesky-network
    restart: unless-stopped

networks:
  acmesky-network:
    driver: bridge
    
